[phases.setup]
nixPkgs = ["nodejs", "php82", "php82Packages.composer"]
aptPkgs = ["php-mongodb"]

[phases.install]
cmds = [
    "pecl channel-update pecl.php.net",
    "pecl install mongodb",
    "docker-php-ext-enable mongodb",
    "composer install --no-dev --optimize-autoloader",
    "npm ci"
]

[phases.build]
cmds = ["npm run build", "php artisan config:cache", "php artisan route:cache", "php artisan view:cache"]

[start]
cmd = "php artisan key:generate --force && php artisan migrate --force && php artisan serve --host=0.0.0.0 --port=$PORT"
