[build]
builder = "dockerfile"
dockerfilePath = ".railway/Dockerfile"

[deploy]
startCommand = "php artisan key:generate --force && php artisan migrate --force && php artisan db:seed --force && php artisan serve --host=0.0.0.0 --port=$PORT"
